require: rubocop-rspec

# Offense count: 4
Metrics/LineLength:
  Max: 95

# Offense count: 6
RSpec/ExampleLength:
  Max: 10

# Offense count: 4
Metrics/BlockLength:
  Max: 70

# Offense count: 11
RSpec/MultipleExpectations:
  Max: 5

# Offense count: 1
Style/UnneededInterpolation:
  Exclude:
    - lib/views/view.rb

# Offense count: 1
Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

# Offense count: 2
Security/Open:
  Exclude:
    - lib/repositories/user_repository.rb
    - lib/repositories/purchase_repository.rb

# Offense count: 4
RSpec/DescribeClass:
  Exclude:
    - spec/purchase_repository_spec.rb
    - spec/user_repository_spec.rb
    - spec/purchase_spec.rb
    - spec/user_spec.rb
